p8510\_hw1
================
joseph Kim
9/29/2021

## Problem 1

###### Create a data frame comprised of:

-   a random sample of size 10 from a standard Normal distribution
-   a logical vector indicating whether elements of the sample are
    greater than 0
-   a character vector of length 10
-   a factor vector of length 10, with 3 different factor “levels”

``` r
library(tidyverse)

dataframe_1 = tibble(
  vec_numeric = rnorm(10, sd=1),
  vec_logical = vec_numeric > 0, 
  vec_char = c("Boy", "Girl", "Tent", "Camp", "Bee", "Dog", "Cat", "Lion", "Ben", "Pool"),
  vec_factor = factor(c("First", "Second", "Third", "Third", "First", "First", "Second", "Second", "Third", "First")
  )
)
```

------------------------------------------------------------------------

##### 1B) Try to take the mean of each variable in your dataframe. What works and what doesn’t?

``` r
##### Checking Means of each variable ###

library(tidyverse)
mean(dataframe_1$vec_numeric)
```

    ## [1] -0.005400836

``` r
mean(dataframe_1$vec_logical)
```

    ## [1] 0.5

``` r
mean(dataframe_1$vec_char)
```

    ## Warning in mean.default(dataframe_1$vec_char): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(dataframe_1$vec_factor)
```

    ## Warning in mean.default(dataframe_1$vec_factor): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

##### You can not take the mean of the vec\_char and vec\_factor because they are not numerical values.

------------------------------------------------------------------------

##### 1C) In some cases, you can explicitly convert variables from one type to another. Write a code chunk that applies the as.numeric function to the logical, character, and factor variables (please show this chunk but not the output). What happens, and why? Does this help explain what happens when you try to take the mean?

``` r
### Coercing variable types 
as.numeric(dataframe_1$vec_logical)
```

    ##  [1] 1 0 1 0 0 0 1 0 1 1

``` r
as.numeric(dataframe_1$vec_char)
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(dataframe_1$vec_factor)
```

    ##  [1] 1 2 3 3 1 1 2 2 3 1

###### By converting variables to be numeric, it converts reoccuring values are numbers values. The vec\_factor values are converted into 1,2, and 3. If we are to pull the means now, they would result in a numerical mean.

------------------------------------------------------------------------

## Problem 2

##### 1a) Loading Penguins Dataset

``` r
data("penguins", package = "palmerpenguins")

nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(na.omit(penguins$flipper_length_mm))
```

    ## [1] 200.9152

This dataset tells us information about certain penguins, presumably by
an individual named Palmer. We are given the species, the name of the
island, bill length (mm), bill depth (mm), flipper length (mm), body
mass (grams), sex, and year.. The dataset consists of 344 rows and 8
columns. The mean flipper length was 200.9152 mm.

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8510_hw1_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->
